### ISSUE TITLE
The test_copy_tree_with_replace unittest checks the `roles:` incorrectly

### ISSUE THREAD

**Issue by spetrosi** [linux-system-roles/auto-maintenance#67]
The `test_copy_tree_with_replace` unit test passes `pre_params` to the `create_test_tree` function, the `pre_params` has one dictionary with `"key": "roles"` that results in such a task file:
```
- name: Ensure that the role runs with default parameters
  hosts: all
  tasks:
    - name: default task
      roles:
        - fedora.system_roles.systemrole
```
This syntax does not exist in Ansible. The reesulting task file must be similar to the following:
```
- name: Ensure that the role runs with default parameters
  hosts: all
  roles:
    - fedora.system_roles.systemrole
```
